services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=daily_tracker'
      - 'MYSQL_ROOT_USER=root'
      - 'MYSQL_USER=user'
      - 'MYSQL_ROOT_PASSWORD=root_password'
      - 'MYSQL_PASSWORD=password'
    ports:
      - '3366:3306'
